customhost = "database-assignment.culwxou6cuaj.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "student"
custombucket = "wongkaryan-student"
customregion = "us-east-1"
